'use strict';
const KEY='gc-branching-v1', app=document.getElementById('app');
let state=null, pending=null, selected=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
try{state=JSON.parse(localStorage.getItem(KEY));if(state&&(state.version!==1||!Array.isArray(state.order)||state.order.some(id=>!CASES.some(c=>c.id===id))))state=null}catch{state=null}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{document.getElementById('storageNotice')?.remove();app.insertAdjacentHTML('beforeend','<p id="storageNotice" class="notice">Tarayıcı kaydı kullanılamıyor; sonuçları indirin ve bu sayfayı kapatmayın.</p>')}}
function home(){document.body.classList.remove("exam-active");document.getElementById("watermark")?.remove();pending=null;selected=null;app.innerHTML=`<div class="card hero"><span class="eyebrow">Genel cerrahi asistanları için</span><h1>Bilgiyi klinik karara dönüştürün.</h1><p>Başlangıç bulgularını değerlendirin, işlem seçin ve yeni klinik durumlara yanıt verin. Her vaka beş temel yeterliği ölçer. Hatalı seçim ek bir yeniden değerlendirme yolunu açar.</p><div class="notice">Bu sürüm bir pilot uygulamadır. Sonuçlar bu tarayıcıda saklanır; merkezi kayıt ve doğrulanmış aday kimliği yoktur. Sınav anahtarı uygulama kaynaklarında bulunabilir. Eğitim sorumlusu klinik içeriği ve puanlamayı gerçek sınavdan önce onaylamalıdır.</div><div class="controls"><label>Ad soyad<input id="candidateName" maxlength="80" placeholder="Ad soyad" autocomplete="off"></label><label>Aday kodu<input id="candidate" maxlength="60" placeholder="Örn. ASİSTAN-001" autocomplete="off"></label><label>Mod<select id="mode"><option value="exam">Sınav — geribildirim en sonda</option><option value="training">Eğitim — her karardan sonra</option></select></label><label>Vaka kapsamı<select id="scope"><option value="all">10 vaka — 60 dakika</option>${CASES.map((c,i)=>`<option value="${c.id}">${i+1}. ${esc(c.title)} — 10 dakika</option>`).join('')}</select></label></div><p class="subtle">Her vaka 100 puan; toplam puan vaka ortalamasıdır. Her ana karar 20, düzeltme 8, kabul edilebilir alternatif 16 puan. Her kritik hata ayrıca 10 puan düşürür. Eşikler pilot için önerilmiştir; klinik olarak doğrulanmış ölçek değildir.</p><label class="row"><input id="fullscreen" type="checkbox" checked style="width:auto">Sınavda tam ekran iste</label><p class="subtle">Sınav sırasında sekme/pencere ve tam ekran değişimleri zaman damgasıyla kaydedilir. Teknik kesinti de olay oluşturabilir; olaylar tek başına kopya kanıtı sayılmaz. Metin seçimi, sağ tık ve kopyalama sınav boyunca kısıtlanır; kimliğiniz filigranda görünür.</p><div class="row"><button class="primary" id="start">Yeni oturum başlat</button>${state?`<button id="resume">${state.finished?'Sonuçları göster':'Kaldığım yerden devam et'}</button>`:''}</div></div><div class="grid">${CASES.map((c,i)=>`<div class="case"><span class="tag">VAKA ${String(i+1).padStart(2,'0')}</span><b>${esc(c.title)}</b><small>5 ana karar · Yeniden değerlendirme dalları</small></div>`).join('')}</div>`;
document.getElementById('start').onclick=()=>{const candidateName=document.getElementById('candidateName').value.trim(),candidate=document.getElementById('candidate').value.trim();if(!candidateName){document.getElementById('candidateName').focus();return}if(!candidate){document.getElementById('candidate').focus();return}if(state&&!confirm('Mevcut oturumun yerini yeni oturum alacak. Önce sonuçları indirmeniz önerilir. Devam edilsin mi?'))return;const scope=document.getElementById('scope').value;state={version:1,id:globalThis.crypto?.randomUUID?.()||'session-'+Date.now(),candidate,candidateName,events:[],fullscreenRequired:document.getElementById('fullscreen').checked,mode:document.getElementById('mode').value,order:scope==='all'?CASES.map(c=>c.id):[scope],caseIndex:0,stage:0,rescue:false,log:[],startedAt:new Date().toISOString(),deadline:Date.now()+(scope==='all'?60:10)*60000,finished:false};save();render();if(state.mode==="exam"&&state.fullscreenRequired)requestFull()};document.getElementById('resume')?.addEventListener('click',render)}
function current(){return CASES.find(c=>c.id===state.order[state.caseIndex])}
function choices(stage,rescue){if(rescue)return shuffle([{kind:'rescue',text:stage.good},{kind:'unsafe',text:'Mevcut plana devam etmek; ek değerlendirme veya müdahale yapmamak'}]);return shuffle([{kind:'good',text:stage.good},{kind:'bad',text:stage.bad},...(stage.alt?[{kind:'alt',text:stage.alt}]:[])])}
function render(){if(!state)return home();if(!state.finished&&Date.now()>=state.deadline)return finish('Süre doldu');if(state.finished)return results();pending=null;selected=null;setProtection();const c=current(),st=c.stages[state.stage],opts=choices(st,state.rescue),decision=state.caseIndex*5+state.stage;app.innerHTML=`<div class="row"><span class="eyebrow">${esc(state.candidate)} · ${state.mode==='exam'?'Sınav':'Eğitim'}</span><span class="timer" id="timer"></span>${state.mode==="exam"&&state.fullscreenRequired?'<button id="full">Tam ekran</button>':''}</div><div class="bar"><span style="width:${decision/(state.order.length*5)*100}%"></span></div><div class="card"><div class="row"><span class="tag">Vaka ${state.caseIndex+1} / ${state.order.length}</span><span class="tag">Karar ${state.stage+1} / 5${state.rescue?' · Yeniden değerlendirme':''}</span></div><h1>${state.mode==='exam'?'Klinik vaka '+(state.caseIndex+1):esc(c.title)}</h1>${state.stage===0&&!state.rescue?`<div class="clinical">${esc(c.opening)}</div>`:''}<h2>${esc(state.rescue?'Klinik yeniden değerlendirme':st.title)}</h2><div class="clinical">${esc(state.rescue?st.rescue:st.clinical)}</div><p>Bu aşamada hangi yaklaşımı seçersiniz?</p><div class="choices">${opts.map((o,i)=>`<button class="choice" data-i="${i}"><span class="letter">${String.fromCharCode(65+i)}</span><span>${esc(o.text)}</span></button>`).join('')}</div><div id="feedback" aria-live="polite"></div><div class="row"><button class="primary" id="confirm" disabled>Kararı uygula</button><button id="stop">Oturumu bitir</button></div><p class="subtle">Kararı uyguladıktan sonra önceki kararı değiştiremezsiniz. Sayfa yenilense de kayıtlı aşamadan devam edilir. Klinik zamanlar senaryo amaçlıdır; gerçek sınav süresi üstte gösterilir.</p></div>`;
app.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{if(pending)return;selected=opts[Number(b.dataset.i)];app.querySelectorAll('.choice').forEach(x=>x.classList.toggle('selected',x===b));document.getElementById('confirm').disabled=false});document.getElementById('confirm').onclick=()=>{if(pending){advance(pending);return}if(!selected)return;applyDecision(selected)};document.getElementById('stop').onclick=()=>{if(confirm('Oturum sonlandırılsın mı? Tamamlanmayan kararlar sıfır puan alır.'))finish('Aday sonlandırdı')};document.getElementById('full')?.addEventListener('click',requestFull);tick()}
function applyDecision(o){if(Date.now()>=state.deadline)return finish('Süre doldu');const c=current(),st=c.stages[state.stage];const critical=(o.kind==='bad'&&st.critical)||o.kind==='unsafe';const pts={good:20,alt:16,bad:0,rescue:8,unsafe:0}[o.kind];const row={caseId:c.id,caseTitle:c.title,stage:state.stage,stageTitle:st.title,rescue:state.rescue,choice:o.text,kind:o.kind,points:pts,critical,explanation:st.explanation,time:new Date().toISOString()};state.log.push(row);const route=o.kind==='bad'?'rescue':o.kind==='unsafe'?'terminate':'next';
// Commit destination before displaying training feedback, so refresh cannot award twice.
move(route);save();if(state.mode==='training'){pending=route;app.querySelectorAll('.choice').forEach(b=>b.disabled=true);document.getElementById('feedback').innerHTML=`<div class="feedback"><b>${pts?`${pts} puan`:'0 puan'}${critical?' · Kritik hata: −10 puan':''}</b><p>${esc(st.explanation)}</p></div>`;document.getElementById('confirm').textContent=state.finished?'Sonuçları göster':'Devam et';document.getElementById('confirm').disabled=false}else render()}
function move(route){if(route==='rescue'){state.rescue=true;return}if(route==='terminate'){state.caseIndex++;state.stage=0;state.rescue=false}else{state.rescue=false;state.stage++;if(state.stage>=5){state.stage=0;state.caseIndex++}}if(state.caseIndex>=state.order.length){state.finished=true;state.reason='Tamamlandı';state.finishedAt=new Date().toISOString()}}
function advance(){render()}
function finish(reason){state.finished=true;state.reason=reason;state.finishedAt=new Date().toISOString();pending=null;save();results()}
function scores(){return state.order.map(id=>{const c=CASES.find(c=>c.id===id),log=state.log.filter(r=>r.caseId===id);const raw=log.reduce((n,r)=>n+r.points,0),critical=log.filter(r=>r.critical).length;return{id,title:c.title,score:Math.max(0,Math.min(100,raw-critical*10)),raw,critical,completed:new Set(log.filter(r=>r.kind!=='bad').map(r=>r.stage)).size}})}
function results(){document.body.classList.remove("exam-active");document.getElementById("watermark")?.remove();const sc=scores(),avg=Math.round(sc.reduce((n,c)=>n+c.score,0)/sc.length),errors=sc.reduce((n,c)=>n+c.critical,0);app.innerHTML=`<div class="card hero"><span class="eyebrow">Oturum sonucu</span><h1>Klinik karar raporu</h1><p>${esc(state.candidateName)} (${esc(state.candidate)}) · ${esc(state.reason)} · ${esc(new Date(state.startedAt).toLocaleString('tr-TR'))}</p><div class="metrics"><div class="metric"><strong>${avg}</strong>Ortalama / 100</div><div class="metric"><strong>${errors}</strong>Kritik hata</div><div class="metric"><strong>${state.log.length}</strong>Kaydedilen karar</div></div><p class="subtle">Bu sonuç başarı/başarısızlık kararı vermez. Puanlama pilot rubriğidir; tamamlanmayan aşamalar sıfır puan alır. Kritik hatalar ayrıca incelenmelidir.</p><div class="row"><button class="primary" id="json">JSON raporu indir</button><button id="csv">CSV sonuç indir</button><button id="print">Yazdır / PDF</button><button id="home">Başlangıca dön</button></div></div><div class="card scroll"><table><thead><tr><th>Vaka</th><th>Puan</th><th>Kritik hata</th><th>Karar aşaması</th></tr></thead><tbody>${sc.map(c=>`<tr><td>${esc(c.title)}</td><td>${c.score}/100</td><td>${c.critical}</td><td>${c.completed}/5</td></tr>`).join('')}</tbody></table></div><div class="card"><h2>Sınav olay kaydı</h2><p class="subtle">${(state.events||[]).length} olay. Bu kayıt yereldir; değiştirilmeye karşı güvenilir sunucu kaydı değildir. Otomatik puan cezası uygulanmaz.</p><details><summary>Olayları göster</summary>${(state.events||[]).map(e=>`<p class="subtle">${esc(new Date(e.time).toLocaleString("tr-TR"))} · ${esc(e.type)} · ${esc(e.detail)}</p>`).join("")||"<p>Olay kaydı yok.</p>"}</details><h2>Karar yolu ve gerekçeler</h2>${sc.map(c=>{const rows=state.log.filter(r=>r.caseId===c.id),source=CASES.find(x=>x.id===c.id).source;return `<details><summary>${esc(c.title)} · ${c.score}/100</summary>${rows.length?rows.map(r=>`<p><b>${r.stage+1}. ${esc(r.stageTitle)}${r.rescue?' — yeniden değerlendirme':''}</b><br>${esc(r.choice)}<br><span class="${r.critical?'danger':'subtle'}">${r.points} puan${r.critical?' · Kritik hata: −10':''}</span></p><p class="subtle">${esc(r.explanation)}</p>`).join(''):'<p>Bu vakada karar kaydı yok.</p>'}<p><a href="${source.url}" target="_blank" rel="noopener">${esc(source.label)}</a></p></details>`}).join('')}</div>`;document.getElementById('json').onclick=()=>download('json',JSON.stringify({...state,scores:sc,average:avg},null,2),'application/json');document.getElementById('csv').onclick=exportCSV;document.getElementById('print').onclick=()=>{app.querySelectorAll('details').forEach(d=>d.open=true);window.print()};document.getElementById('home').onclick=home}
function download(ext,content,type){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download='klinik-sinav-'+state.id+'.'+ext;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function exportCSV(){const safe=v=>{v=String(v??'');if(/^[=+\-@\t\r]/.test(v))v="'"+v;return '"'+v.replace(/"/g,'""')+'"'};const header=['Oturum','Aday','Mod','Vaka','Aşama','Yeniden değerlendirme','Seçim','Puan','Kritik hata','Zaman','Gerekçe'];const rows=state.log.map(r=>[state.id,state.candidate,state.mode,r.caseTitle,r.stage+1,r.rescue,r.choice,r.points,r.critical,r.time,r.explanation]);(state.events||[]).forEach(e=>rows.push([state.id,state.candidate,state.mode,'OLAY',e.type,'',e.detail,'','',e.time,'']));scores().forEach(c=>rows.push([state.id,state.candidate,state.mode,c.title,'VAKA TOPLAMI','','',c.score,c.critical,'','']));download('csv','\ufeff'+[header,...rows].map(r=>r.map(safe).join(';')).join('\r\n'),'text/csv;charset=utf-8')}
function tick(){if(!state||state.finished)return;const remaining=state.deadline-Date.now();if(remaining<=0){finish('Süre doldu');return}const t=document.getElementById('timer');if(t){const secs=Math.ceil(remaining/1000);t.textContent=`${Math.floor(secs/60)}:${String(secs%60).padStart(2,'0')}`;t.classList.toggle('danger',secs<120)}}
function protectedExam(){return !!(state&&!state.finished&&state.mode==='exam'&&document.body.classList.contains('exam-active'))}
function eventLog(type,detail=''){if(!state||state.finished||state.mode!=='exam')return;state.events??=[];state.events.push({type,detail,time:new Date().toISOString(),caseId:state.order[state.caseIndex],stage:state.stage+1});save()}
function setProtection(){const active=state.mode==='exam';document.body.classList.toggle('exam-active',active);document.getElementById('watermark')?.remove();if(active){const mark=document.createElement('div');mark.id='watermark';mark.setAttribute('aria-hidden','true');for(let i=0;i<12;i++){const span=document.createElement('span');span.textContent=(state.candidateName||'')+' · '+state.candidate;mark.appendChild(span)}document.body.appendChild(mark)}}
async function requestFull(){try{if(document.documentElement.requestFullscreen){await document.documentElement.requestFullscreen();eventLog('Tam ekran isteği','Başarılı')}else eventLog('Tam ekran desteklenmiyor','Tarayıcı bu APIyi sunmuyor')}catch{eventLog('Tam ekran isteği başarısız','Tarayıcı isteği reddetti')}}
for(const type of ['contextmenu','selectstart','dragstart','copy','cut'])document.addEventListener(type,e=>{if(protectedExam()){e.preventDefault();eventLog('Engellenen işlem',type)}},true);
document.addEventListener('keydown',e=>{if(protectedExam()&&(e.ctrlKey||e.metaKey)&&['c','x','a'].includes(e.key.toLowerCase())){e.preventDefault();eventLog('Engellenen kısayol',e.key.toUpperCase())}},true);
document.addEventListener('visibilitychange',()=>eventLog(document.hidden?'Sekme gizlendi':'Sekme görünür'));
window.addEventListener('blur',()=>eventLog('Pencere odağı kayboldu'));
window.addEventListener('focus',()=>eventLog('Pencere odağı geri geldi'));
document.addEventListener('fullscreenchange',()=>eventLog(document.fullscreenElement?'Tam ekrana giriş':'Tam ekrandan çıkış'));
window.addEventListener('pagehide',()=>eventLog('Sayfadan ayrılma / yenileme'));
setInterval(tick,1000);home();
