'use strict';
const app=document.getElementById('app'),CFG=window.EXAM_CONFIG||{},KEY='gc-v2-session';
let session=null, selected=null,busy=false;const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
try{session=JSON.parse(localStorage.getItem(KEY))}catch{}
function save(){try{localStorage.setItem(KEY,JSON.stringify(session));return true}catch{return false}}
async function api(action,payload={}){const r=await fetch(CFG.apiUrl,{method:'POST',headers:{'Content-Type':'application/json',apikey:CFG.publishableKey||''},body:JSON.stringify({action,token:session?.token,...payload})});const d=await r.json();if(!r.ok)throw Error(d.error||'İşlem tamamlanamadı');return d}
function message(t){const el=document.getElementById('message');if(el)el.textContent=t}
function home(){document.body.classList.remove('exam-active');document.getElementById('watermark')?.remove();app.innerHTML=`<div class="card hero"><span class="eyebrow">Genel cerrahi asistanları için</span><h1>Her karar, yeni bir klinik aşama.</h1><p>Hastayı değerlendirin, yaklaşımınızı seçin ve yeni bulgulara göre kararınızı güncelleyin.</p><div class="metrics"><div class="metric"><strong>8</strong>Klinik vaka</div><div class="metric"><strong>4 + 4</strong>Poliklinik ve acil</div><div class="metric"><strong>60 dk</strong>Tam sınav süresi</div></div><div class="notice">${CFG.apiUrl?'Aday kodunuzla sınava giriş yapın. Cevaplar sunucuya kaydedilir; puan ve kişisel değerlendirme sınav tamamlandığında açılır.':'Deneme sürümü · Yeni sınav henüz etkin değil. Bu eski deneme bankasının standart puanlaması henüz tamamlanmamıştır.'}</div><div class="controls"><label>Ad soyad<input id="name" maxlength="80" autocomplete="name" placeholder="Adınız ve soyadınız"></label><label>Aday kodu<input id="code" maxlength="100" autocomplete="off" placeholder="${CFG.apiUrl?'Size verilen giriş kodu':'Deneme için istediğiniz kod'}"></label>${CFG.apiUrl?'':`<label>Vaka kapsamı<select id="scope"><option value="all">8 vakanın tamamı</option>${DEMO_BANK.cases.map(c=>`<option value="${c.id}">${esc(c.title)}</option>`).join('')}</select></label>`}</div><label class="row"><input id="full" type="checkbox" checked style="width:auto">Tam ekran modunu kullan</label><p class="subtle">Seçme, kopyalama, sağ tık ve sürükleme sınav sırasında kısıtlanır. Sekme, odak ve tam ekran değişimleri kaydedilir. Adınız ve kodunuz filigranda gösterilir. Teknik olaylar otomatik kopya veya ceza kararı oluşturmaz.</p><p id="message" class="danger" role="status"></p><div class="row"><button id="start" class="primary">${CFG.apiUrl?'Sınava başla':'Denemeye başla'}</button>${session?'<button id="resume">Son oturuma dön</button>':''}</div></div><div class="grid">${DEMO_BANK.cases.map((c,i)=>`<div class="case"><span class="tag">VAKA ${String(i+1).padStart(2,'0')}</span><b>${esc(c.title)}</b><small>Değerlendirme · Tanı · Tedavi · İzlem</small></div>`).join('')}</div>`;
document.getElementById('start').onclick=start;document.getElementById('resume')?.addEventListener('click',resume)}
async function start(){if(busy)return;if(!CFG.apiUrl&&!DEMO_BANK.first){message('Yeni 8 vakalık sınavın içerik aktarımı sürüyor. Önceki vaka bankası kullanımdan kaldırıldı.');return;}const name=document.getElementById('name').value.trim(),code=document.getElementById('code').value.trim(),full=document.getElementById('full').checked;if(!name||!code){message('Ad soyad ve aday kodunu doldurun.');return}if(session&&!session.finished&&!confirm('Kayıtlı oturumunuz var. Yeni oturuma geçilsin mi?'))return;busy=true;document.getElementById('start').disabled=true;try{if(CFG.apiUrl){const d=await api('start',{code,name});session={...d,remote:true,full,events:[]}}else{const scope=document.getElementById('scope').value,id=crypto.randomUUID();session={id,name,code,scope,remote:false,full,events:[],log:[],nodeId:scope==='all'?DEMO_BANK.first:DEMO_BANK.cases.find(c=>c.id===scope).first,deadline:Date.now()+(scope==='all'?60:10)*60000,finished:false};setDemoNode()}if(!save()){session=null;throw Error('Tarayıcı kayıt izni gerekli. Lütfen normal bir tarayıcı penceresi kullanın.')}render();if(full)requestFull()}catch(e){message(e.message);document.getElementById('start').disabled=false}finally{busy=false}}
function setDemoNode(){const n=DEMO_BANK.nodes[session.nodeId];if(!n){session.finished=true;session.node=null;return}session.node={...n,options:shuffle(n.options)}}
async function resume(){if(busy)return;busy=true;try{if(session.remote){if(!CFG.apiUrl)throw Error('Sunucu bağlantısı ayarlanmamış.');Object.assign(session,await api('state'));save()}render();if(session.full&&!session.finished)requestFull()}catch(e){message(e.message)}finally{busy=false}}
function protect(){document.body.classList.toggle('exam-active',!session.finished);document.getElementById('watermark')?.remove();if(session.finished)return;const mark=document.createElement('div');mark.id='watermark';mark.setAttribute('aria-hidden','true');for(let i=0;i<12;i++){const s=document.createElement('span');s.textContent=session.name+' · '+session.code;mark.appendChild(s)}document.body.appendChild(mark)}
function render(){selected=null;if(!session)return home();if(session.finished)return end();if(Date.now()>session.deadline){finish('timeout');return}protect();const n=session.node,all=session.scope==='all'||session.remote,count=all?8:1,idx=all?n.caseNumber:1,progress=(idx-1)/count;app.innerHTML=`<div class="row"><span class="eyebrow">${esc(session.name)} · ${session.remote?'Sınav':'Deneme'}</span><span id="timer" class="timer"></span>${session.full?'<button id="fullscreen">Tam ekran</button>':''}</div><div class="bar"><span style="width:${progress*100}%"></span></div><div class="card"><div class="row"><span class="tag">Vaka ${idx} / ${count}</span><span class="tag">Karar ${n.stage}</span><span class="tag">${session.remote?'Sunucuya kaydediliyor':'Bu cihazda kayıtlı'}</span></div><h1>Klinik vaka ${idx}</h1>${n.opening?`<div class="clinical">${esc(n.opening)}</div>`:''}<div class="clinical">${esc(n.clinical)}</div><h2>${esc(n.title).replace(/^Soru\s+[0-9]+[A-Z]?:\s*/, '')}</h2><div class="choices">${n.options.map((o,i)=>`<button class="choice" data-i="${i}" aria-pressed="false"><span class="letter">${String.fromCharCode(65+i)}</span><span>${esc(o.text)}</span></button>`).join('')}</div><p id="message" class="danger" role="status"></p><div class="row"><button id="confirm" class="primary" disabled>Kararı uygula ve devam et</button><button id="finish">Oturumu bitir</button></div><p class="subtle">Uygulanan karar değiştirilemez. Seçiminiz hastanın sonraki klinik durumunu belirler. Puanlar ve cevap gerekçeleri sınav tamamlandıktan sonra açılır.</p></div>`;app.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{if(busy)return;selected=n.options[Number(b.dataset.i)];app.querySelectorAll('.choice').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b))});document.getElementById('confirm').disabled=false});document.getElementById('confirm').onclick=answer;document.getElementById('finish').onclick=()=>{if(confirm('Oturumu bitirmek istediğinizden emin misiniz?'))finish('candidate')};document.getElementById('fullscreen')?.addEventListener('click',requestFull);tick()}
async function answer(){if(!selected||busy)return;busy=true;const button=document.getElementById('confirm');button.disabled=true;button.textContent='Karar kaydediliyor…';try{const node=session.node,o=selected;if(session.remote){const d=await api('answer',{nodeId:node.id,optionId:o.id,events:session.events||[]});Object.assign(session,d);session.events=[]}else{if(Date.now()>=session.deadline){session.finished=true;session.reason='timeout'}else{session.log.push({nodeId:node.id,caseId:node.caseId,stage:node.stage,rescue:node.rescue,optionId:o.id,choice:o.text,time:new Date().toISOString()});const next=DEMO_BANK.nodes[o.next];session.nodeId=o.next;if(!next||(session.scope!=='all'&&next.caseId!==session.scope)){session.finished=true;session.reason='completed'}else setDemoNode()}}save();render()}catch(e){message('Karar kaydedilemedi. '+e.message+' Aynı kararı tekrar gönderebilirsiniz.');button.disabled=false;button.textContent='Yeniden gönder'}finally{busy=false}}
async function finish(reason){if(busy)return;busy=true;try{if(session.remote){Object.assign(session,await api('finish',{reason,events:session.events||[]}));session.events=[]}else{session.finished=true;session.reason=reason;session.finishedAt=new Date().toISOString()}save();end()}catch(e){message('Oturum sonlandırılamadı: '+e.message)}finally{busy=false}}
function end(){protect();const r=session.report;app.innerHTML=`<div class="card hero"><span class="eyebrow">Oturum tamamlandı</span><h1>${r?esc(r.displayTotal)+' / 100':'Kararlarınız kaydedildi.'}</h1><p>${esc(session.name)}</p>${r?`<p>${r.incomplete?'Sınav eksik tamamlandı. Yanıtlanmayan alanlar sıfır katkıyla toplamda tutuldu.':'Tüm değerlendirme alanları tamamlandı.'}</p><div class="metrics">${r.areas.map(a=>`<div class="metric"><strong>${a.score.toFixed(1)} / 25</strong>${esc(a.title)}</div>`).join('')}</div><h2>Gelişim hedefleri</h2><ul>${r.learningGoals.map(g=>`<li>${esc(g)}</li>`).join('')}</ul>${r.cases.map(c=>`<section class="report-case"><h2>${esc(c.title)} · ${c.score.toFixed(1)} / 100</h2>${c.decisions.map((d,i)=>`<article><h3>Karar ${i+1}</h3><p>${esc(d.clinical)}</p><p><b>${esc(d.question)}</b></p><p>Seçiminiz: ${esc(d.choice)}</p><p>Vaka puanına katkı: ${d.contribution.toFixed(2)}</p><p>${esc(d.feedback)}</p>${d.outcome?`<p>Hasta seyri: ${esc(d.outcome)}</p>`:''}</article>`).join('')}</section>`).join('')}`:`<div class="notice">${esc(session.reportError||'Bu eski deneme bankasının puan haritası tamamlanmamış. Karar kaydınızı indirebilirsiniz; puan üretilmedi.')}</div>`}<div class="row no-print">${r?'<button id="print">Raporu PDF olarak kaydet</button>':''}<button id="download">${r?'Rapor verisini indir':'Karar kaydını indir'}</button><button id="home" class="primary">Başlangıca dön</button></div></div>`;document.getElementById('home').onclick=home;document.getElementById('print')?.addEventListener('click',()=>window.print());document.getElementById('download').onclick=()=>{const {node,token,...record}=session;download('sinav-raporu-'+session.id+'.json',JSON.stringify(r||record,null,2))}}
function download(name,text){const u=URL.createObjectURL(new Blob([text],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function active(){return !!(session&&!session.finished&&document.body.classList.contains('exam-active'))}
function eventLog(type,detail=''){if(!active())return;session.events??=[];if(session.events.length<500)session.events.push({id:crypto.randomUUID(),type,detail,time:new Date().toISOString()});save();if(session.remote)flushEvents()}
let flushing=false;async function flushEvents(){if(flushing||!session?.remote||!session.events?.length)return;flushing=true;const batch=session.events.slice();try{await api('events',{events:batch});const ids=new Set(batch.map(e=>e.id));session.events=session.events.filter(e=>!ids.has(e.id));save()}catch{}finally{flushing=false}}
async function requestFull(){try{if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else eventLog('Tam ekran desteklenmiyor')}catch{eventLog('Tam ekran isteği reddedildi')}}
for(const type of ['contextmenu','selectstart','dragstart','copy','cut'])document.addEventListener(type,e=>{if(active()){e.preventDefault();eventLog('Engellenen işlem',type)}},true);
document.addEventListener('keydown',e=>{if(active()&&(e.ctrlKey||e.metaKey)&&['c','x','a'].includes(e.key.toLowerCase())){e.preventDefault();eventLog('Engellenen kısayol',e.key.toUpperCase())}},true);
document.addEventListener('visibilitychange',()=>eventLog(document.hidden?'Sekme gizlendi':'Sekme görünür'));window.addEventListener('blur',()=>eventLog('Pencere odağı kayboldu'));window.addEventListener('focus',()=>eventLog('Pencere odağı geri geldi'));document.addEventListener('fullscreenchange',()=>eventLog(document.fullscreenElement?'Tam ekrana giriş':'Tam ekrandan çıkış'));window.addEventListener('pagehide',()=>eventLog('Sayfadan ayrılma / yenileme'));
function tick(){if(!active())return;const secs=Math.max(0,Math.ceil((session.deadline-Date.now())/1000)),t=document.getElementById('timer');if(t){t.textContent=`${Math.floor(secs/60)}:${String(secs%60).padStart(2,'0')}`;t.classList.toggle('danger',secs<120)}if(secs===0&&!busy)finish('timeout')}
setInterval(tick,1000);setInterval(flushEvents,10000);home();
